FightBox:
  kickbox:
    identifiers: kickbox
    icon_name: hdfightbox_icon_pl.png
    description: "kickbox"
  sumo:
    identifiers: sumo
    icon_name: hdfightbox_icon_pl.png
    description: "sumo"
  wrestling:
    identifiers: wrestling
    icon_name: hdfightbox_icon_pl.png
    description: "zápas"
  karate:
    identifiers: karate
    icon_name: hdfightbox_icon_pl.png 
    description: "karate"

FashionBox:
  lookbook:
    identifiers: lookbook
    icon_name: hdfashion_icon_pl.png
    description: "lookbook"
  fashion_cities:
    identifiers: "fashion cities"
    icon_name: hdfashion_icon_pl.png
    description: "módní m?st"
  vintage:
    identifiers: vintage
    icon_name: hdfashion_icon_pl.png
    description: "vinobraní"
  homme:
    identifiers: homme
    icon_name: hdfashion_icon_pl.png
    description: "mu"
  femme:
    identifiers: femme
    icon_name: hdfashion_icon_pl.png
    description: "ena"
  fashion_candies:
    identifiers: "fashion candies"
    icon_name: hdfashion_icon_pl.png
    description: "módní bonbóny"

DocuBox:
  historical: 
    identifiers: historical
    icon_name: hddocubox_icon_pl.png
    description: "historický"
  roads:
    identifiers: roads
    icon_name: hddocubox_icon_pl.png
    description: "silnice"
  documentary:
    identifiers: documentary
    icon_name: hddocubox_icon_pl.png
    description: "dokumentární"

FilmPackage:
  scifi:
    identifiers: scifi
    icon_name: sci-fi_pl.png
    description: "sci-fi"
  comedy:
    identifiers: comedy, komedi
    icon_name: comedy_pl.png
    description: "komedie"
  romance:
    identifiers: romance, romans
    icon_name: romance_pl.png
    description: "romance"
  action:
    identifiers: action, akcja
    icon_name: action_pl.png
    description: "actian"
  drama:
    identifiers: drama, dramat
    icon_name: drama_pl.png
    description: "drama"
  thriller:
    identifiers: thriller
    icon_name: thriller_pl.png
    description: "detektivka"
  horror: 
    identifiers: horror
    icon_name: horror_pl.png
    description: "hr?za"
  family:
    identifiers: family, familijny
    icon_name: family_pl.png
    description: "rodina"
  documentary:
    identifiers: documentary, dokument
    icon_name: documentary_pl.png
    description: "dokumentární"
  animated:
    identifiers: animated, animation, animowany
    icon_name: animation_pl.png
    description: "ivý"
  recommended:
    identifiers: recommended, poleca
    icon_name: recommended_pl.png
    description: "doporu?uje"
    
UltimatePackage:
  scifi:
    identifiers: scifi
    icon_name: sci-fi_pl.png  
    description: "sci-fi"
  comedy:
    identifiers: comedy, komedi
    icon_name: comedy_pl.png
    description: "komedie"
  romance:
    identifiers: romance, romans
    icon_name: romance_pl.png
    description: "romance"
  action:
    identifiers: action, akcja
    icon_name: action_pl.png
    description: "akce"
  drama:
    identifiers: drama, dramat
    icon_name: drama_pl.png
    description: "drama"
  thriller:
    identifiers: thriller
    icon_name: thriller_pl.png
    description: "detektivka"
  horror: 
    identifiers: horror
    icon_name: horror_pl.png
    description: "hr?za"
  family:
    identifiers: family, familijny
    icon_name: family_pl.png
    description: "rodina"
  documentary:
    identifiers: documentary, dokument
    icon_name: documentary_pl.png
    description: "dokumentární"
  animated:
    identifiers: animated, animation, animowany
    icon_name: animation_pl.png
    description: "ivý"
  recommended:
    identifiers: recommended, poleca
    icon_name: recommended_pl.png
    description: "ajánlott"
  kickbox:
    identifiers: kickbox
    icon_name: hdfightbox_icon_pl.png
    description: "kickbox"
  sumo:
    identifiers: sumo
    icon_name: hdfightbox_icon_pl.png
    description: "sumo"
  wrestling:
    identifiers: wrestling
    icon_name: hdfightbox_icon_pl.png
    description: "zápas"
  karate:
    identifiers: karate
    icon_name: hdfightbox_icon_pl.png
    description: "karate"
  lookbook:
    identifiers: lookbook
    icon_name: hdfashion_icon_pl.png
    description: "lookbook"
  fashion_cities:
    identifiers: "fashion cities"
    icon_name: hdfashion_icon_pl.png
    description: "módní m?st"
  vintage:
    identifiers: vintage
    icon_name: hdfashion_icon_pl.png
    description: "vinobraní"
  homme:
    identifiers: homme
    icon_name: hdfashion_icon_pl.png
    description: "mu"
  femme:
    identifiers: femme
    icon_name: hdfashion_icon_pl.png
    description: "ena"
  fashion_candies:
    identifiers: "fashion candies"
    icon_name: hdfashion_icon_pl.png
    description: "módní bonbóny"
  historical: 
    identifiers: historical
    icon_name: hddocubox_icon_pl.png
    description: "historický"
  roads:
    identifiers: roads
    icon_name: hddocubox_icon_pl.png
    description: "silnice"
  documentary:
    identifiers: documentary
    icon_name: hddocubox_icon_pl.png
    description: "dokumentární"

PolishPackage:
  recommended: 
    identifiers: recommended, poleca
    icon_name: recommended_pl.png
    description: "doporu?uje"
  top_movies:
    identifiers: movie, movies
    icon_name: top_movies_pl.png
    description: "top filmy"
