FightBox:
  kickbox:
    identifiers: kickbox
    icon_name: hdfightbox_icon_pl.png
    description: "kickbox"
  sumo:
    identifiers: sumo
    icon_name: hdfightbox_icon_pl.png
    description: "sumo"
  wrestling:
    identifiers: wrestling
    icon_name: hdfightbox_icon_pl.png
    description: "güre?"
  karate:
    identifiers: karate
    icon_name: hdfightbox_icon_pl.png 
    description: "karate"

FashionBox:
  lookbook:
    identifiers: lookbook
    icon_name: hdfashion_icon_pl.png
    description: "lookbook"
  fashion_cities:
    identifiers: "fashion cities"
    icon_name: hdfashion_icon_pl.png
    description: "moda ?ehirleri"
  vintage:
    identifiers: vintage
    icon_name: hdfashion_icon_pl.png
    description: "ba?bozumu"
  homme:
    identifiers: homme
    icon_name: hdfashion_icon_pl.png
    description: "adam"
  femme:
    identifiers: femme
    icon_name: hdfashion_icon_pl.png
    description: "kad?n"
  fashion_candies:
    identifiers: "fashion candies"
    icon_name: hdfashion_icon_pl.png
    description: "moda ?ekerler"

DocuBox:
  historical: 
    identifiers: historical
    icon_name: hddocubox_icon_pl.png
    description: "hostorical"
  roads:
    identifiers: roads
    icon_name: hddocubox_icon_pl.png
    description: "yollar"
  documentary:
    identifiers: documentary
    icon_name: hddocubox_icon_pl.png
    description: "belgesel"

FilmPackage:
  scifi:
    identifiers: scifi
    icon_name: sci-fi_pl.png
    description: "bilimkurgu"
  comedy:
    identifiers: comedy, komedi
    icon_name: comedy_pl.png
    description: "komeda"
  romance:
    identifiers: romance, romans
    icon_name: romance_pl.png
    description: "romantizm"
  action:
    identifiers: action, akcja
    icon_name: action_pl.png
    description: "eylem"
  drama:
    identifiers: drama, dramat
    icon_name: drama_pl.png
    description: "drama"
  thriller:
    identifiers: thriller
    icon_name: thriller_pl.png
    description: "gerilim"
  horror: 
    identifiers: horror
    icon_name: horror_pl.png
    description: "korku"
  family:
    identifiers: family, familijny
    icon_name: family_pl.png
    description: "aile"
  documentary:
    identifiers: documentary, dokument
    icon_name: documentary_pl.png
    description: "belgesel"
  animated:
    identifiers: animated, animation, animowany
    icon_name: animation_pl.png
    description: "canland?r?lm??"
  recommended:
    identifiers: recommended, poleca
    icon_name: recommended_pl.png
    description: "tavsiye"
    
UltimatePackage:
  scifi:
    identifiers: scifi
    icon_name: sci-fi_pl.png  
    description: "bilimkurgu"
  comedy:
    identifiers: comedy, komedi
    icon_name: comedy_pl.png
    description: "komedi"
  romance:
    identifiers: romance, romans
    icon_name: romance_pl.png
    description: "romantizm"
  action:
    identifiers: action, akcja
    icon_name: action_pl.png
    description: "eylem"
  drama:
    identifiers: drama, dramat
    icon_name: drama_pl.png
    description: "dramat"
  thriller:
    identifiers: thriller
    icon_name: thriller_pl.png
    description: "gerilim"
  horror: 
    identifiers: horror
    icon_name: horror_pl.png
    description: "korku"
  family:
    identifiers: family, familijny
    icon_name: family_pl.png
    description: "aile"
  documentary:
    identifiers: documentary, dokument
    icon_name: documentary_pl.png
    description: "belgesel"
  animated:
    identifiers: animated, animation, animowany
    icon_name: animation_pl.png
    description: "canland?r?lm??"
  recommended:
    identifiers: recommended, poleca
    icon_name: recommended_pl.png
    description: "tavsiye"
  kickbox:
    identifiers: kickbox
    icon_name: hdfightbox_icon_pl.png
    description: "kickbox"
  sumo:
    identifiers: sumo
    icon_name: hdfightbox_icon_pl.png
    description: "sumo"
  wrestling:
    identifiers: wrestling
    icon_name: hdfightbox_icon_pl.png
    description: "güre?"
  karate:
    identifiers: karate
    icon_name: hdfightbox_icon_pl.png
    description: "karate"
  lookbook:
    identifiers: lookbook
    icon_name: hdfashion_icon_pl.png
    description: "lookbook"
  fashion_cities:
    identifiers: "fashion cities"
    icon_name: hdfashion_icon_pl.png
    description: "moda ?ehirleri"
  vintage:
    identifiers: vintage
    icon_name: hdfashion_icon_pl.png
    description: "ba?bozumu"
  homme:
    identifiers: homme
    icon_name: hdfashion_icon_pl.png
    description: "adam"
  femme:
    identifiers: femme
    icon_name: hdfashion_icon_pl.png
    description: "kad?n"
  fashion_candies:
    identifiers: "fashion candies"
    icon_name: hdfashion_icon_pl.png
    description: "moda ?ekerler"
  historical: 
    identifiers: historical
    icon_name: hddocubox_icon_pl.png
    description: "tarihsel"
  roads:
    identifiers: roads
    icon_name: hddocubox_icon_pl.png
    description: "yollar"
  documentary:
    identifiers: documentary
    icon_name: hddocubox_icon_pl.png
    description: "belgesel"

PolishPackage:
  recommended: 
    identifiers: recommended, poleca
    icon_name: recommended_pl.png
    description: "tavsiye"
  top_movies:
    identifiers: movie, movies
    icon_name: top_movies_pl.png
    description: "en iyi filmleri"
